In [1]:
import pandas as pd

data = {
    "Name": ["Aisha","Tunde","Kemi","David"],
    "Age": [22,25,23,24],
    "Salary":[50000,65000,60000,70000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0  Aisha   22   50000
1  Tunde   25   65000
2   Kemi   23   60000
3  David   24   70000

In [2]:
Product: Phone, Laptop, Tablet
Price: 500, 1200, 300

SyntaxError: invalid syntax (4020683475.py, line 1)

In [3]:
import pandas as pd

data = {
    "Product": ["Phone","Laptop","Tablet"],
    "Age": [500,1200,300],
    }

df = pd.DataFrame(data)

df

  Product   Age
0   Phone   500
1  Laptop  1200
2  Tablet   300